#!/bin/bash

source run_common_env.sh

NUM_PROC=$((`nproc`/2))
echo "NUM THREADS FOR CPU PROCESS: $NUM_PROC"
export OMP_NUM_THREADS=$NUM_PROC
export OPENBLAS_NUM_THREADS=$NUM_PROC

export XBLAS_USE_CBLAS=1
export CAFFE_XLNX_USE_DEFAULT_SGEMM=1
#export XBLAS_SKIP_POOL5_CPOST=0

export CAFFE_XLNX_DO_GEMM_PREP_B=1
unset CAFFE_XLNX_DO_FPGA_IM2COL
